### ISSUE TITLE
Get and display data from "database"

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#2]
Our app is very simple: a single page, essentially, that displays info on currently know trials for Ebola. We are not going to implement a proper database at this stage, for the following reasons:
1. We have very very small data requirements
2. We are building a prototype
3. We want to leverage existing tools for data entry

So, we will use a Google Spreadsheet as the database :).

We have other apps that store data in Google Spreadsheets. The basic idea is this:
- Have data in a Spreadsheet
- Certain users can edit/update data directly in the spreadsheet
- We "publish the sheet as CSV" and make it "public on the web" - these are settings in Google Spreadsheets
- The app directly queries from the CSV, builds a JSON array from the data therein, and then exposes the data as JSON via a dedicated endpoint

For reference, here is a [set of utilities for reading from a CSV](https://github.com/okfn/opendatacensus/blob/develop/census/loaders/utils.js), and here are some [functions that take the data from CSV, process it and save it to a database](https://github.com/okfn/opendatacensus/blob/develop/census/loaders/index.js). (**note**: In _this_ app, we are not saving to a database! we will read directly from the CSV/Spreadsheet)
# Tasks

Here is the data in [spreadsheet form](https://docs.google.com/spreadsheets/d/18QoNBtABuGca8LBc0nXjMfrzWz4gZ2FWlLmtrvX-qyo/edit#gid=0), and [here is the "as CSV" version of the same data](https://docs.google.com/spreadsheets/d/18QoNBtABuGca8LBc0nXjMfrzWz4gZ2FWlLmtrvX-qyo/pub?gid=0&single=true&output=csv)
- [x] Add a config module to the codebase ([see](https://github.com/okfn/opentrials-prototype/commit/56fd81f29f85bd2ed4e4e68230e4e9eb85be6dd2))
  - [x] Add a config setting called `trackerData` that can also be set from the `TRACKER_DATA` env var
  - [x] The value of `trackerData` will be the URL of the CSV file
- [x] Write a service that reads from the given Tracker Data CSV, and transforms the data into a JSON Array (each row is an object, etc.)
- [x] Write a new `controllers/api.js` module which has a `trackerData` controller. This controller calls the service and returns a JSON response like `{results: [... the data array ...]}`
- [x] Hook up the controller to a route: `/api/data`
- [x] Write a functional test for the new API route
- [x] Write a unit test(s) for the `trackerData` service 

Note that in the various links I give above, you'll see use of the [`csv`](http://csv.adaltas.com) module and [`bluebird`](https://github.com/petkaantonov/bluebird) module. These are great Node libraries to get to know a bit for the type of work we do :).
