### ISSUE TITLE
Setup CI flow from Shippable to Heroku

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#3]
# Tasks
- [x] Configure yaml file for shippable
  - https://app.shippable.com/projects/5604ab341895ca447417f6fe
- [x] Configure the flow from shippable build to Heroku deploy
  - [x] Only deploy from master branch
  - [x] Document the process
- [x] Integrate Shippable badge to README
- [x] As well as test runner, setup code coverage to run on shippable
