### ISSUE TITLE
Database updates

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#52]
# Description

We recently had an overhaul of the database for this app. This changed the structure and data, and the app itself is now not displaying data due to these changes.

# Tasks

- [x] Update existing mappers for the new database structure (Trials and Deaths files)
- [x] Just get the data working, as you'll get a chance to tidy up further when refactoring in https://github.com/opentrials/tracker-ebola/issues/59
- [x] Identify any fields that are not exposed to the UI; list them in this issue as a comment

**Comment by zhenyab** [comment]
Fields of trials not in use:

recruitment
study_design
conditions
interventions
age_groups
phases
results_first_received
results_last_searched
url_results
primary_completion_date
publication_delay_days
country
secondary_registry_or_id
correspondence
