### ISSUE TITLE
More data and ui enhancements

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#53]
# Description

We had a refresh of the data for the Ebola Trials tracker. We want to touch up a few issues in the UI too.

# Tasks

- [x] Make any tweaks to header/footer/chart/body to make it look reasonably good on handheld devices
- [x] Integrate OKI Panel and Cookie Bar, and tweak design as appropriate
- [x] Main navigation item changes:
  - [x] New item: "Methods and Results"
  - [x] Size, design, etc. something not quite right?
- [x] Add a section to the main body (smallish in height? more like a toolbar/breadcrumb size thing? Not sure) that says "READ OUR PAPER: We've published our methods and results for the Ebola Trial Tracker project." Links to same place as "Methods and Results" in main nav. Destination TBD.
- [x] Leader board section: updates for each Trial element
  - [x] Labels / pills / buttons directly under the title for each of "Start date" | "Completion date" | "Open Trials entry" | "Registry entry" | "Correspondence with trialist"
  - [x] Other things to tidy up these elements?? Up to you @smth

**Comment by smth** [comment]
@pwalsh are "Open Trials entry" | "Registry entry" | "Correspondence with trialist" just links with those labels?

**Comment by pwalsh** [comment]
Correct.

**Comment by smth** [comment]
Thanks. I'm leaving the hrefs for these empty, assuming someone will add them later.

Similarly, what does "Methods and Results" link to? Is there some content to add to the page?

**Comment by pwalsh** [comment]
It will link to a Google Sheet.

**Comment by smth** [comment]
I've made a [PR](https://github.com/opentrials/tracker-ebola/pull/58) addressing all of the above. I have deviated from the suggestions a little, most notably the "Read our paper" link. I think the below makes sense. Thoughts?
![ebola-trials](https://cloud.githubusercontent.com/assets/1375708/15773602/c0b549e2-296f-11e6-84a2-4db5bed1e98d.jpg)

**Comment by pwalsh** [comment]
@smth great work as always. thanks.
