### ISSUE TITLE
Trial correspondence via the app

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#54]
# Description

As part of chasing up information on these Ebola Trials, especially the ones without any published results, we've built a body of correspondence. We want this correspondence available on the web app. 

There will be a single page for correspondence per trial, and it will be linked to from the trial from the results table on the main page of the app. This means users will be able to not only see the basic trial metadata we have collected, but also the dialogue we've had in trying to get clarity on trial status for many trials.

The correspondence is organised in a Google Drive folder, with each file in the folder named after the identifier of the trial it belongs to. This means we can use the Google Drive API to get the list of files in our Trial Correspondence folder, and select a file using the trial id.

There is a "data structure" in these files (a pattern using headings). We'll likely try to parse them a little for some basic formatting. First though, let's just get them out of the file, and served inside an HTML webpage.

## Resources

- [Node lib for Google APIs](https://developers.google.com/drive/v3/web/quickstart/nodejs)
- [Drive API reference](https://developers.google.com/drive/v3/reference/)
- [The folder on our Google Drive](https://drive.google.com/drive/folders/0B2ccvtjUol6LQktDc0RzTmwtelk)

# Tasks

- [x] Prep a self-contained module that is configured against a "folder" identifier from Drive, and treats the enclosed files as a collection. The consuming code passes a string, being the name of the file, and gets back the *contents* of the file
  - [x] It is important that this is a self-contained package: we'll extract this out into a standalone library when we establish the API here, as we have a need for exactly this in another current project as well
- [x] Expose a route base `correspondence/{id}` which called our custom drive module and returns an HTML page, in our app template, with the contents of the file in the content section
  - [x] Identify what we need to do to clean the output - are we actually able to get the plain text out of the Google Doc files?
- [x] Some very basic unit tests - don't need to go overboard here

**Comment by pwalsh** [comment]
@vitorbaptista any comments?

**Comment by vitorbaptista** [comment]
@pwalsh I haven't used the Google Drive API, so I don't know how easy would that be. Unless it's trivial, I would prefer to convert that manually to a Google Sheet or something with a bit more structure, avoiding too much magic :smile:

**Comment by pwalsh** [comment]
@vitorbaptista I get it, but I really need this same functionality exactly also for the IBP work, so totally worth it for us. 

It is trivially easy to get the content as plain text out of a Google Doc via the Drive API. See here to try: https://developers.google.com/drive/v3/reference/files/export#try-it

**Comment by vitorbaptista** [comment]
Fair enough. Looks good to me, then :+1:

**Comment by zhenyab** [comment]
@pwalsh To start working on Drive API need to [turn on Drive API](https://developers.google.com/drive/v2/web/quickstart/nodejs#step_1_turn_on_the_api_name).

**Comment by pwalsh** [comment]
@zhenyab sent details to slack
