### ISSUE TITLE
Improvements to the Backend > JSON serialization

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#6]
# Tasks
- [x] Some of the data fields are lists, separated by a pipe |. Convert these into arrays
- [x] Ensure that dates are formatted from source > JSON in a consistent manner (they probably are by the looks of it, once you fix https://github.com/okfn/opentrials-ebola-tracker/issues/5), but please do check
- [x] Check other fields  - does it look like we need to do any further processing to make our JSON objects nice?
