### ISSUE TITLE
General app UI

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#9]
# Tasks

**Do not implement the chart as yet** :). We'll wait for the additional data we will require (https://trello.com/c/mKdYn3Y7/128-source-data-on-ebola-deaths), as this will likely change what we want to display and how.
- [x] Make the API call to get the data and display the list of trials tracked as per the UI mocks
  - [x] Use lodash for templating the JSON to HTML (https://lodash.com/docs#template). I guess we'll just use jQuery for the XHR now... we might move to a frontend framework if we see the app develop further
  - [x] Write a simple poller that checks the API point every 5 minutes, and updates if the data has changed
  - [x] Have a simple loader animation on place of the list while waiting for data 
  - [x] Generate hat fragment of "Statistics" text, with appropriate changes (eg: our data currently has two different sources, so the logic for making the sentence should support that)
- [x] Replace the "XML" download button from the mocks with a "JSON" download button that goes directly to the data endpoint
- [x] Write 1-2 functional/integration tests using Zombie.js for the display of the data feed
- [x] Integrate About and Overview texts. Requires delivery from @danfowler
